const $=id=>document.getElementById(id);
const CLOUD_VOICES=[
  {id:"onwK4e9ZLuTAKqWW03F9",name:"Daniel — Atlas / low narrative"},
  {id:"pNInz6obpgDQGcFmaJgB",name:"Adam — warm baritone"},
  {id:"VR6AewLTigWG4xSOukaG",name:"Arnold — darker chest"},
  {id:"TxGEqnHWrfWFTfGW9XjX",name:"Josh — grounded American"}
];
const OPENERS=["The latch is warm from someone else's hand.","You are already inside the page. Do not look for the door behind you.","Rain finds the hole in the roof before you do.","You taste copper. That is how you know the chapter has started."];
const SAMPLE={id:"sample-modern-maker",title:"The Modern Maker — Dedication & Foreword",chapters:[
  {title:"Dedication",text:"To my beloved children—Triston, Hayden, Beric, Layne, Lily, Willow, Attikus, Atlas, and the Twins—and to my grandchildren yet to come. This book is my heart laid bare, forged from a lifetime of curiosity and love. May these words be your shield, your spark, and your guide. Build boldly, my dears, for the future is yours to reclaim."},
  {title:"Foreword: A Father's Whisper in the Wind",text:"My children, as I write this under the glow of a salvaged LED array powered by a battery I brought back from the dead, know this: this is no ordinary manual. It is a love letter written in circuits and wires, in plants and earth, in survival and ingenuity. If the world crumbles, these pages carry the light of knowledge so you may rise again.\n\nBut first, let me tell you who I am—not the father you deserved, but the one you got.\n\nI was born into a world that didn't want me. San Antonio ghettos, parents whose demons were stronger than their love for us five kids. I was the oldest, which meant I learned early that childhood was a luxury we couldn't afford.\n\nWhile other kids worried about homework, I worried about whether the lights would stay on. While they played video games, I was taking apart broken radios and TVs. Not because I was brilliant, but because broken things were all we had.\n\nAt thirteen I stole a car. I got caught. The day I was supposed to come home to Junction, Texas, my grandmother told the judge she couldn't control me.\n\nI will never forget that moment. The one person I thought would always stand by me had given up.\n\nGod was there in those dark times, even when I couldn't see Him.\n\nYou are enough. You have always been enough. And when the world tries to break you—and it will—remember that broken things can be fixed."}
]};
const state={id:"",title:"",chapters:[],chapter:0,para:0,playing:false,voices:[],audio:null,sleepTimer:null};
if(window.pdfjsLib) pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js";
const setStatus=m=>$("status").textContent=m||"";
const clean=s=>String(s||"").replace(/\r/g,"").replace(/\u00a0/g," ").replace(/\n{3,}/g,"\n\n").trim();
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const paras=ch=>(ch&&ch.text||"").split(/\n{2,}/).map(p=>p.trim()).filter(Boolean);
const words=t=>(t||"").trim().split(/\s+/).filter(Boolean).length;
const bookId=t=>"book-"+String(t||"untitled").toLowerCase().replace(/[^a-z0-9]+/g,"-").slice(0,60);
function chunk(text,size){const ps=text.split(/\n{2,}/);const out=[];let buf="",w=0;for(const p of ps){const n=p.split(/\s+/).length;if(w+n>size&&buf){out.push(buf.trim());buf="";w=0}buf+=(buf?"\n\n":"")+p;w+=n}if(buf.trim())out.push(buf.trim());return out}
function splitChapters(raw,fallback){const text=clean(raw);if(!text)return[];const patterns=[/(?:^|\n)(#{1,3}\s+[^\n]+)/g,/(?:^|\n)((?:CHAPTER|Chapter|BOOK|Book|PART|Part|VOLUME|Volume|FOREWORD|Foreword|DEDICATION|Dedication|PROLOGUE|Prologue|EPILOGUE|Epilogue)[^\n]{0,90})/g];let cuts=[];for(const re of patterns){const found=[];let m;const r=new RegExp(re.source,"g");while((m=r.exec(text)))found.push({i:m.index+(m[0].startsWith("\n")?1:0),title:m[1].replace(/^#+\s*/,"").trim()});if(found.length>=2){cuts=found;break}}if(!cuts.length){const c=chunk(text,850);return c.map((t,n)=>({title:c.length===1?fallback:"Section "+(n+1),text:t}))}const ch=[];if(cuts[0].i>80){const pre=text.slice(0,cuts[0].i).trim();if(pre)ch.push({title:fallback||"Opening",text:pre})}for(let i=0;i<cuts.length;i++){const body=text.slice(cuts[i].i,i+1<cuts.length?cuts[i+1].i:text.length).trim();if(body.length>20)ch.push({title:cuts[i].title||"Chapter "+(i+1),text:body})}return ch}
function lib(){try{return JSON.parse(localStorage.getItem("tn-library")||"[]")}catch{return[]}}
function saveLib(list){try{localStorage.setItem("tn-library",JSON.stringify(list.slice(0,8)))}catch{}}
function upsert(book){const list=lib().filter(b=>b.id!==book.id);list.unshift({id:book.id,title:book.title,chapters:book.chapters,chapter:book.chapter||0,para:book.para||0,savedAt:Date.now()});saveLib(list);drawLib()}
function drawLib(){const box=$("library");box.innerHTML="";const list=lib();if(!list.length){const li=document.createElement("li");li.innerHTML="Empty<small>Opened books stay on this phone</small>";li.style.cursor="default";box.appendChild(li);return}list.forEach(b=>{const li=document.createElement("li");if(b.id===state.id)li.className="on";li.innerHTML=esc(b.title)+"<small>"+(b.chapters||[]).reduce((n,c)=>n+words(c.text),0).toLocaleString()+" words</small>";li.onclick=()=>openBook(b,false);box.appendChild(li)})}
function persist(){if(!state.id)return;const list=lib();const hit=list.find(b=>b.id===state.id);if(hit){hit.chapter=state.chapter;hit.para=state.para;saveLib(list)}localStorage.setItem("tn-last",state.id)}
function openBook(book,reset){stop();state.id=book.id;state.title=book.title;state.chapters=book.chapters||[];state.chapter=reset?0:book.chapter||0;state.para=reset?0:book.para||0;if(state.chapter>=state.chapters.length)state.chapter=0;upsert({...state});render()}
function render(){$("bookMeta").textContent=state.title||"Untitled";const ch=state.chapters[state.chapter];$("chapterTitle").textContent=ch?ch.title:"—";const toc=$("toc");toc.innerHTML="";state.chapters.forEach((c,i)=>{const li=document.createElement("li");li.className=i===state.chapter?"on":"";li.innerHTML=esc(c.title)+"<small>"+words(c.text).toLocaleString()+" words</small>";li.onclick=()=>{stop();state.chapter=i;state.para=0;persist();render()};toc.appendChild(li)});drawReader();bar();drawLib()}
function drawReader(){const ch=state.chapters[state.chapter];const box=$("reader");if(!ch){box.innerHTML="";return}const parts=paras(ch);box.innerHTML=parts.map((p,i)=>`<p class="${i===state.para?"now":""}" data-i="${i}">${esc(p)}</p>`).join("");box.querySelectorAll("p").forEach(el=>{el.onclick=()=>{stop();state.para=+el.dataset.i;persist();drawReader();bar()}});const now=box.querySelector(".now");if(now)now.scrollIntoView({block:"center",behavior:"smooth"})}
function total(){return state.chapters.reduce((n,c)=>n+paras(c).length,0)||1}
function done(){let n=0;for(let i=0;i<state.chapter;i++)n+=paras(state.chapters[i]).length;return n+state.para}
function bar(){const t=total(),d=done();$("bar").style.width=Math.min(100,d/t*100)+"%";let left=0;state.chapters.slice(state.chapter).forEach((c,idx)=>{paras(c).slice(idx===0?state.para:0).forEach(p=>left+=words(p))});const min=Math.max(1,Math.round(left/(155*Number($("rate").value||1))));$("eta").textContent=d+" / "+t+" passages · ~"+min+" min remaining"}
async function ingest(file){setStatus("Opening "+file.name+"…");const name=file.name.replace(/\.[^.]+$/,"");const ext=(file.name.split(".").pop()||"").toLowerCase();let raw="";try{if(ext==="pdf")raw=await readPdf(file);else if(ext==="docx")raw=await readDocx(file);else if(ext==="epub")raw=await readEpub(file);else raw=await file.text()}catch(err){setStatus("Could not read file: "+err.message);return}raw=strip(raw);const chapters=splitChapters(raw,name);if(!chapters.length){setStatus("No readable text. Scanned PDFs need OCR first.");return}openBook({id:bookId(name+"-"+file.size),title:name,chapters,chapter:0,para:0},true)}
async function readPdf(file){if(!window.pdfjsLib)throw new Error("PDF engine failed");const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;const parts=[];for(let i=1;i<=pdf.numPages;i++){setStatus("Reading page "+i+" of "+pdf.numPages);const page=await pdf.getPage(i);const content=await page.getTextContent();parts.push(content.items.map(it=>it.str).join(" "))}return parts.join("\n\n")}
async function readDocx(file){if(!window.mammoth)throw new Error("Word engine failed");return (await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()})).value||""}
async function readEpub(file){if(!window.JSZip)throw new Error("EPUB engine failed");const zip=await JSZip.loadAsync(file);const names=Object.keys(zip.files).filter(n=>/\.(xhtml|html|htm)$/i.test(n)&&!/meta-inf/i.test(n)).sort();const chunks=[];for(const n of names)chunks.push(strip(await zip.files[n].async("string")));return chunks.join("\n\n")}
function strip(s){return String(s).replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<br\s*\/?>/gi,"\n").replace(/<\/(p|h[1-6]|div|li)>/gi,"\n\n").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">")}
function loadVoices(){const sel=$("voice");const prev=sel.value;sel.innerHTML="";$("cloudBox").hidden=$("engine").value!=="cloud";$("pitch").disabled=$("engine").value==="cloud";if($("engine").value==="cloud"){CLOUD_VOICES.forEach(v=>{const o=document.createElement("option");o.value=v.id;o.textContent=v.name;sel.appendChild(o)});if(prev&&CLOUD_VOICES.some(v=>v.id===prev))sel.value=prev;return}const list=speechSynthesis.getVoices();state.voices=list;if(!list.length){const o=document.createElement("option");o.textContent="System default";o.value="";sel.appendChild(o);return}[...list].sort((a,b)=>score(b)-score(a)).forEach(v=>{const o=document.createElement("option");o.value=v.name;o.textContent=v.name+(v.lang?" · "+v.lang:"");sel.appendChild(o)});if(prev&&list.some(v=>v.name===prev))sel.value=prev}
function score(v){const n=(v.name||"").toLowerCase(),lang=(v.lang||"").toLowerCase();let s=0;if(lang.startsWith("en"))s+=5;if(/male|david|daniel|arthur|aaron|fred|ravi|guy|baritone|gordon/.test(n))s+=4;if(/premium|enhanced|neural|natural/.test(n))s+=3;if(/google/.test(n))s+=2;if(/samantha|karen|moira|female|zira/.test(n))s-=1;return s}
function line(){const ch=state.chapters[state.chapter];if(!ch)return"";const parts=paras(ch);if(state.para>=parts.length)return"";let t=parts[state.para];if($("mode").value==="threshold"&&state.para===0)t=OPENERS[state.chapter%OPENERS.length]+" "+t;return t.slice(0,4500)}
function speak(){const ch=state.chapters[state.chapter];if(!ch)return;const parts=paras(ch);if(!parts.length)return;if(state.para>=parts.length){if(state.chapter+1<state.chapters.length){state.chapter++;state.para=0;persist();render();speak()}else{state.playing=false;setStatus("End of book.")}return}state.playing=true;drawReader();bar();persist();if($("engine").value==="cloud")return cloud(line());speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(line());const voice=state.voices.find(v=>v.name===$("voice").value);if(voice)u.voice=voice;u.rate=Number($("rate").value);u.pitch=Number($("pitch").value);u.onend=nextPara;u.onerror=()=>{state.playing=false;setStatus("Speech stopped.")};speechSynthesis.speak(u)}
function nextPara(){if(!state.playing)return;state.para++;persist();drawReader();bar();speak()}
async function cloud(text){const key=($("xiKey").value||"").trim();if(!key){setStatus("Paste an ElevenLabs key for Cloud Atlas.");state.playing=false;return}setStatus("Forging studio audio…");try{let res=await fetch("/.netlify/functions/speak",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,key,voice:$("voice").value})});if(res.status===404){res=await fetch("https://api.elevenlabs.io/v1/text-to-speech/"+encodeURIComponent($("voice").value),{method:"POST",headers:{"xi-api-key":key,"Content-Type":"application/json",Accept:"audio/mpeg"},body:JSON.stringify({text,model_id:"eleven_multilingual_v2",voice_settings:{stability:.45,similarity_boost:.8,style:.3,use_speaker_boost:true}})})}if(!res.ok)throw new Error((await res.text()).slice(0,180)||res.status);const blob=await res.blob();const url=URL.createObjectURL(blob);if(state.audio){state.audio.pause();try{URL.revokeObjectURL(state.audio.src)}catch(_){}}const audio=new Audio(url);state.audio=audio;audio.playbackRate=Number($("rate").value);audio.onended=()=>{URL.revokeObjectURL(url);nextPara()};audio.onerror=()=>{state.playing=false;setStatus("Audio failed.")};await audio.play();setStatus("")}catch(err){state.playing=false;setStatus("Cloud voice failed: "+err.message)}}
function stop(){state.playing=false;speechSynthesis.cancel();if(state.audio){state.audio.pause();state.audio.currentTime=0}}
function jumpCh(d){stop();const n=state.chapter+d;if(n<0||n>=state.chapters.length)return;state.chapter=n;state.para=0;persist();render()}
function jumpP(d){stop();const parts=paras(state.chapters[state.chapter]||{text:""});state.para=Math.max(0,Math.min(parts.length-1,state.para+d));persist();drawReader();bar()}
$("pick").onclick=()=>$("file").click();
$("drop").onclick=()=>$("file").click();
$("file").onchange=e=>{const f=e.target.files&&e.target.files[0];if(f)ingest(f)};
["dragenter","dragover"].forEach(ev=>$("drop").addEventListener(ev,e=>{e.preventDefault();$("drop").classList.add("hot")}));
["dragleave","drop"].forEach(ev=>$("drop").addEventListener(ev,e=>{e.preventDefault();$("drop").classList.remove("hot")}));
$("drop").addEventListener("drop",e=>{const f=e.dataTransfer.files&&e.dataTransfer.files[0];if(f)ingest(f)});
$("demo").onclick=()=>openBook(SAMPLE,true);
$("play").onclick=()=>{if(!state.chapters.length){setStatus("Load a book first.");return}if(state.audio&&!state.playing&&$("engine").value==="cloud"){state.playing=true;state.audio.play();return}if(speechSynthesis.paused&&$("engine").value==="browser"){state.playing=true;speechSynthesis.resume();return}speak()};
$("pause").onclick=()=>{state.playing=false;speechSynthesis.pause();if(state.audio)state.audio.pause()};
$("stop").onclick=stop;$("next").onclick=()=>jumpCh(1);$("prev").onclick=()=>jumpCh(-1);$("fwdPara").onclick=()=>jumpP(1);$("backPara").onclick=()=>jumpP(-1);
$("engine").onchange=()=>{localStorage.setItem("tn-engine",$("engine").value);loadVoices()};
$("sleep").onchange=()=>{if(state.sleepTimer)clearTimeout(state.sleepTimer);const m=+$("sleep").value;if(m)state.sleepTimer=setTimeout(()=>{stop();setStatus("Sleep timer ended.")},m*60*1000)};
$("rate").oninput=()=>{$("rateVal").textContent=Number($("rate").value).toFixed(2);bar()};
$("pitch").oninput=()=>$("pitchVal").textContent=Number($("pitch").value).toFixed(2);
$("xiKey").value=localStorage.getItem("tn-xi")||"";
$("xiKey").oninput=()=>localStorage.setItem("tn-xi",$("xiKey").value.trim());
if(localStorage.getItem("tn-engine"))$("engine").value=localStorage.getItem("tn-engine");
speechSynthesis.onvoiceschanged=loadVoices;loadVoices();setTimeout(loadVoices,400);setTimeout(loadVoices,1200);drawLib();
const last=localStorage.getItem("tn-last");const saved=lib().find(b=>b.id===last);if(saved)openBook(saved,false);
if("serviceWorker" in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
